spring:
  data:
    elasticsearch:
        cluster-name: elasticsearch/reference/index
        cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
            #properties:
                #path:
                    #logs: ./elasticsearch/log #elasticsearch日志存储目录
                    #data: ./elasticsearch/data #elasticsearch数据存储目录
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: admin
    password: admin
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug